"""
Auto-generated transformer modules for ES to BBF Salesforce migration.

This package contains Python modules with transformation functions for
converting EverStream (ES) field values to BlueBird Fiber (BBF) format.

Usage:
    # Import specific transformer module
    from transformers.account_transformers import TRANSFORMERS, apply_transformers

    # Apply all transformers to an ES record
    bbf_record = apply_transformers(es_record)

    # Apply single transformer
    bbf_value = TRANSFORMERS['Payment_Terms__c'](es_record['Payment_Terms__c'])

Generated by: transformation-generator agent
"""

__all__ = []
