#!/usr/bin/env python3
"""
Auto-generated transformation functions for ES Account to BBF Account migration.

Generated by: transformation-generator agent
Date: 2026-01-15T17:10:04.302439
Source: ES_Account_to_BBF_Account_mapping.xlsx

Usage:
    from transformers.account_transformers import TRANSFORMERS, apply_transformers

    # Apply single transformer
    bbf_value = TRANSFORMERS['proposalmanager__Primary_State__c'](es_record['Legally_Organized_Under__c'])

    # Apply all transformers
    bbf_record = apply_transformers(es_record)
"""

import re
from typing import Any, Optional
from datetime import datetime, date


# Picklist value mappings
TYPE_MAP = {
    'Customer': 'Enterprise',
    'Sales Prospect': 'Enterprise',
    'Vendor': 'Vendor',
    'Customer (MDU Residential)': 'Enterprise',
    'Other': 'Other',
    'Customer (Wholesaler Carrier)': 'Wholesale'
}

BILLINGGEOCODEACCURACY_MAP = {
    'Address': 'Address',
    'NearAddress': 'NearAddress',
    'Block': 'Block',
    'Street': 'Street',
    'ExtendedZip': 'ExtendedZip',
    'Zip': 'Zip',
    'Neighborhood': 'Neighborhood',
    'City': 'City',
    'County': 'County',
    'State': 'State',
    'Unknown': 'Unknown'
}

SHIPPINGGEOCODEACCURACY_MAP = {
    'Address': 'Address',
    'NearAddress': 'NearAddress',
    'Block': 'Block',
    'Street': 'Street',
    'ExtendedZip': 'ExtendedZip',
    'Zip': 'Zip',
    'Neighborhood': 'Neighborhood',
    'City': 'City',
    'County': 'County',
    'State': 'State',
    'Unknown': 'Unknown'
}

INDUSTRY_MAP = {
    'Accommodation': 'Accommodation',
    'Administrative': 'Administrative',
    'Agriculture': 'Agriculture',
    'Arts': 'Business Services',
    'Construction & Engineering': 'Construction & Engineering',
    'Educational': 'Education',
    'Finance': 'Finance',
    'Government': 'Government',
    'Health care': 'Healthcare',
    'Management': 'Management',
    'Manufacturing': 'Manufacturing',
    'Mining': 'Mining',
    'Not For Profit': 'Organizations',
    'Other': 'Other',
    'Professional Services': 'Business Services',
    'Real Estate': 'Real Estate',
    'Research & Technology': 'Technology',
    'Retail': 'Retail',
    'Transportation': 'Transportation',
    'Utilities': 'Utilities',
    'Wholesale': 'Wholesale'
}

OWNERSHIP_MAP = {
    'Public': 'Public',
    'Private': 'Private',
    'Subsidiary': 'Subsidiary',
    'Other': 'Other'
}

RATING_MAP = {
    'Hot': 'Hot',
    'Warm': 'Warm',
    'Cold': 'Cold'
}

ACCOUNTSOURCE_MAP = {
    'Agent': 'Agent',
    'CoStar': 'ZoomInfo',
    'Directly Engaged': 'Direct Contact',
    'Inbound Phone Call': 'Inbound Web',
    'Network Map Leads': 'Marketing Campaign',
    'Neustar': 'Neustar',
    'Sales Intern Lead Source': 'Direct Contact',
    'Tidio - Website Chatbot': 'Website',
    'Unsolicited Prospecting': 'Direct Contact',
    'Vendor Referral Program': 'Vendor',
    'Zoominfo': 'Zoominfo'
}

LEAD_SOURCE_MAP = {
    'Agent': 'Agent',
    'CoStar': 'CoStar',
    'Directly Engaged': 'Direct Contact',
    'Inbound Phone Call': 'Inbound Phone Call',
    'Network Map Leads': 'Network Map Leads',
    'Neustar': 'Neustar',
    'Sales Intern Lead Source': 'Direct Contact',
    'Tidio - Website Chatbot': 'Website',
    'Unsolicited Prospecting': 'Direct Contact',
    'Vendor Referral Program': 'Vendor Referral Program',
    'Zoominfo': 'Zoominfo'
}

CLASSIFICATION_ACCOUNT_MAP = {
    'Customer': 'Customer',
    'Sales Prospect': 'Sales Prospect',
    'Vendor': 'Vendor',
    'Customer (MDU Residential)': 'Customer (MDU Residential)',
    'Other': 'Other',
    'Customer (Wholesaler Carrier)': 'Customer (Wholesaler Carrier)'
}

PROPOSALMANAGER__MSA_ON_FILE_MAP = {
    'Pending external approval': 'Pending external approval',
    'Pending internal approval': 'Pending internal approval',
    'Legal Review': 'Legal Review',
    'Executed – on File': 'Executed – on File'
}

CONTRACT_TYPE_MAP = {
    'MSA': 'MSA',
    'IRU': 'IRU'
}

COMPANY_TYPE_MAP = {
    'Corporation': 'Corporation',
    'LLC': 'LLC',
    'Municipal Entity (City, County, Township, Village, etc.)': 'Municipal Entity (City, County, Township, Village, etc.)',
    'Non-Profit (501c)': 'Non-Profit (501c)',
    'General Partnership': 'General Partnership',
    'Sole Proprietor': 'Sole Proprietor'
}

BUSINESSUNIT_MAP = {
    'Everstream Ohio': 'Everstream Ohio',
    'Everstream Michigan': 'Everstream Michigan',
    'Michigan-LB': 'Michigan-LB',
    'OneCommunity': 'OneCommunity',
    'Michigan-RF': 'Michigan-RF',
    'Everstream PA': 'Everstream PA'
}


def transform_proposalmanager_primary_state(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Legally_Organized_Under__c to BBF proposalmanager__Primary_State__c.

    ES Field: Legally_Organized_Under__c (Legally Organized Under)
    ES Type: picklist

    BBF Field: proposalmanager__Primary_State__c (Primary State)
    BBF Type: multipicklist
    BBF Required: No

    AI Reasoning:
    Primary state - ES uses Legally Organized Under

    Args:
        es_value: The source value from ES Legally_Organized_Under__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF proposalmanager__Primary_State__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return PROPOSALMANAGER__PRIMARY_STATE_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_proposalmanager_tax_exempt(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Sales_Tax_Exemption__c to BBF proposalmanager__Tax_Exempt__c.

    ES Field: Sales_Tax_Exemption__c (Sales Tax Exemption)
    ES Type: boolean

    BBF Field: proposalmanager__Tax_Exempt__c (Tax Exempt)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Tax exemption status

    Args:
        es_value: The source value from ES Sales_Tax_Exemption__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF proposalmanager__Tax_Exempt__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_business_unit(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES OneCommunity_Entity__c to BBF Business_Unit__c.

    ES Field: OneCommunity_Entity__c (Entity)
    ES Type: picklist

    BBF Field: Business_Unit__c ((dep) Business Unit)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Business unit/entity mapping

    Args:
        es_value: The source value from ES OneCommunity_Entity__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Business_Unit__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_full_company_name(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Company_Legal_Name__c to BBF Full_Company_Name__c.

    ES Field: Company_Legal_Name__c (Company Legal Name)
    ES Type: textarea

    BBF Field: Full_Company_Name__c (Full Company Name)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Full legal company name

    Args:
        es_value: The source value from ES Company_Legal_Name__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Full_Company_Name__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


# Transformer registry
TRANSFORMERS = {
    'proposalmanager__Primary_State__c': transform_proposalmanager_primary_state,
    'proposalmanager__Tax_Exempt__c': transform_proposalmanager_tax_exempt,
    'Business_Unit__c': transform_business_unit,
    'Full_Company_Name__c': transform_full_company_name
}

# Field mapping (BBF -> ES)
FIELD_MAPPING = {
    'proposalmanager__Primary_State__c': 'Legally_Organized_Under__c',
    'proposalmanager__Tax_Exempt__c': 'Sales_Tax_Exemption__c',
    'Business_Unit__c': 'OneCommunity_Entity__c',
    'Full_Company_Name__c': 'Company_Legal_Name__c'
}


def apply_transformers(es_record: dict) -> dict:
    """
    Apply all transformers to an ES record.

    Args:
        es_record: Dictionary of ES field values (field API name -> value)

    Returns:
        Dictionary of transformed BBF field values (BBF field API name -> value)
    """
    bbf_record = {}

    for bbf_field, transformer in TRANSFORMERS.items():
        es_field = FIELD_MAPPING.get(bbf_field)
        if es_field and es_field in es_record:
            try:
                bbf_record[bbf_field] = transformer(es_record[es_field], es_record)
            except Exception as e:
                # Log error but continue with other fields
                print(f"Warning: Transform failed for {bbf_field}: {e}")
                bbf_record[bbf_field] = None

    return bbf_record
