#!/usr/bin/env python3
"""
Auto-generated transformation functions for ES Billing_Invoice__c to BBF BAN__c migration.

Generated by: transformation-generator agent
Date: 2026-01-15T17:10:04.411158
Source: ES_Billing_Invoice__c_to_BBF_BAN__c_mapping.xlsx

Usage:
    from transformers.ban_transformers import TRANSFORMERS, apply_transformers

    # Apply single transformer
    bbf_value = TRANSFORMERS['Billing_State__c'](es_record['Billing_State__c'])

    # Apply all transformers
    bbf_record = apply_transformers(es_record)
"""

import re
from typing import Any, Optional
from datetime import datetime, date


# Picklist value mappings
PAYMENT_TERMS_MAP = {
    'NET30,NET45,NET60': 'NET 30',
    'NET90': 'NET 60'
}

BILLING_STATE_MAP = {
    '[All 53 state values]': '[All 53 state values]'
}

INVTYPE_MAP = {
    'Paper': 'Print',
    'E-mail': 'Email'
}

BILLING_SCHEDULE_GROUP_MAP = {
    'Monthly': 'Monthly',
    'Manual': 'Manual'
}


def transform_billing_state(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Billing_State__c to BBF Billing_State__c.

    ES Field: Billing_State__c (Billing State)
    ES Type: picklist

    BBF Field: Billing_State__c (Billing State)
    BBF Type: string
    BBF Required: Yes

    AI Reasoning:
    Exact API name match. Type mismatch requires transformer.

    Args:
        es_value: The source value from ES Billing_State__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Billing_State__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return ''

    # Pass through with basic type handling
    return es_value


def transform_invtype(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Invoice_Delivery_Preference__c to BBF invType__c.

    ES Field: Invoice_Delivery_Preference__c (Invoice Delivery Preference)
    ES Type: picklist

    BBF Field: invType__c (Invoice Type)
    BBF Type: picklist
    BBF Required: Yes

    AI Reasoning:
    Invoice delivery method - requires value transformation (Paper/Email -> Print/Email/Both/Manual)

    Args:
        es_value: The source value from ES Invoice_Delivery_Preference__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF invType__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return INVTYPE_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_billing_schedule_group(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Invoice_cycle_cd__c to BBF Billing_Schedule_Group__c.

    ES Field: Invoice_cycle_cd__c (Billing Cycle)
    ES Type: picklist

    BBF Field: Billing_Schedule_Group__c (Billing Schedule Group)
    BBF Type: picklist
    BBF Required: Yes

    AI Reasoning:
    Billing schedule - requires value transformation (Manual/Monthly -> Monthly/Annual/Semiannual)

    Args:
        es_value: The source value from ES Invoice_cycle_cd__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Billing_Schedule_Group__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return BILLING_SCHEDULE_GROUP_MAP.get(es_str, es_str)  # Return original if no mapping


# Transformer registry
TRANSFORMERS = {
    'Billing_State__c': transform_billing_state,
    'invType__c': transform_invtype,
    'Billing_Schedule_Group__c': transform_billing_schedule_group
}

# Field mapping (BBF -> ES)
FIELD_MAPPING = {
    'Billing_State__c': 'Billing_State__c',
    'invType__c': 'Invoice_Delivery_Preference__c',
    'Billing_Schedule_Group__c': 'Invoice_cycle_cd__c'
}


def apply_transformers(es_record: dict) -> dict:
    """
    Apply all transformers to an ES record.

    Args:
        es_record: Dictionary of ES field values (field API name -> value)

    Returns:
        Dictionary of transformed BBF field values (BBF field API name -> value)
    """
    bbf_record = {}

    for bbf_field, transformer in TRANSFORMERS.items():
        es_field = FIELD_MAPPING.get(bbf_field)
        if es_field and es_field in es_record:
            try:
                bbf_record[bbf_field] = transformer(es_record[es_field], es_record)
            except Exception as e:
                # Log error but continue with other fields
                print(f"Warning: Transform failed for {bbf_field}: {e}")
                bbf_record[bbf_field] = None

    return bbf_record
