#!/usr/bin/env python3
"""
Auto-generated transformation functions for ES Contact to BBF Contact migration.

Generated by: transformation-generator agent
Date: 2026-01-15T17:10:04.454832
Source: ES_Contact_to_BBF_Contact_mapping.xlsx

Usage:
    from transformers.contact_transformers import TRANSFORMERS, apply_transformers

    # Apply single transformer
    bbf_value = TRANSFORMERS['Contact_Type__c'](es_record['Contact_Type__c'])

    # Apply all transformers
    bbf_record = apply_transformers(es_record)
"""

import re
from typing import Any, Optional
from datetime import datetime, date


# Picklist value mappings
SALUTATION_MAP = {
    'Mr.': 'Mr.',
    'Ms.': 'Ms.',
    'Mrs.': 'Mrs.',
    'Dr.': 'Dr.',
    'Prof.': 'Prof.'
}

OTHERGEOCODEACCURACY_MAP = {
    'Address': 'Address',
    'NearAddress': 'NearAddress',
    'Block': 'Block',
    'Street': 'Street',
    'ExtendedZip': 'ExtendedZip',
    'Zip': 'Zip',
    'Neighborhood': 'Neighborhood',
    'City': 'City',
    'County': 'County',
    'State': 'State',
    'Unknown': 'Unknown'
}

MAILINGGEOCODEACCURACY_MAP = {
    'Address': 'Address',
    'NearAddress': 'NearAddress',
    'Block': 'Block',
    'Street': 'Street',
    'ExtendedZip': 'ExtendedZip',
    'Zip': 'Zip',
    'Neighborhood': 'Neighborhood',
    'City': 'City',
    'County': 'County',
    'State': 'State',
    'Unknown': 'Unknown'
}

LEADSOURCE_MAP = {
    'Agent': 'Agent',
    'CoStar': 'CoStar',
    'Directly Engaged': 'Direct Contact',
    'Inbound Phone Call': 'Inbound Web',
    'Network Map Leads': 'Network Map Leads',
    'Neustar': 'Neustar',
    'Sales Intern Lead Source': 'Employee Referral',
    'Tidio - Website Chatbot': 'Website',
    'Unsolicited Prospecting': 'Direct Contact',
    'Vendor Referral Program': 'Vendor',
    'Zoominfo': 'ZoomInfo'
}

CONTACT_TYPE_MAP = {
    'Payable': 'Payable',
    'Unknown': 'Prospect',
    'Billing': 'Billing',
    'Decision Maker': 'Executive',
    'Maintenance': 'Maintenance',
    'On-Site': 'Hands & Feet',
    'Order': 'Service Order',
    'Portal User': 'Main',
    'Repair': 'Technician'
}


def transform_contact_type(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Contact_Type__c to BBF Contact_Type__c.

    ES Field: Contact_Type__c (Contact Type)
    ES Type: multipicklist

    BBF Field: Contact_Type__c (Contact Type)
    BBF Type: multipicklist
    BBF Required: No

    AI Reasoning:
    Contact Type multipicklist - both orgs have this field. ES values: Payable, Unknown, Billing, Decision Maker, Maintenance, On-Site, Order, Portal User, Repair. BBF values: Alternate Local Contact, Badge Admin, Billing, Consultant, Engineering, Executive, Hands & Feet, Local Contact, Main, Maintenance, Prospect, Provisioning, Service Order, Site Manager, Technical, Technician, Testing. Some overlap (Billing, Maintenance), needs value translation.

    Args:
        es_value: The source value from ES Contact_Type__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Contact_Type__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return CONTACT_TYPE_MAP.get(es_str, es_str)  # Return original if no mapping


# Transformer registry
TRANSFORMERS = {
    'Contact_Type__c': transform_contact_type
}

# Field mapping (BBF -> ES)
FIELD_MAPPING = {
    'Contact_Type__c': 'Contact_Type__c'
}


def apply_transformers(es_record: dict) -> dict:
    """
    Apply all transformers to an ES record.

    Args:
        es_record: Dictionary of ES field values (field API name -> value)

    Returns:
        Dictionary of transformed BBF field values (BBF field API name -> value)
    """
    bbf_record = {}

    for bbf_field, transformer in TRANSFORMERS.items():
        es_field = FIELD_MAPPING.get(bbf_field)
        if es_field and es_field in es_record:
            try:
                bbf_record[bbf_field] = transformer(es_record[es_field], es_record)
            except Exception as e:
                # Log error but continue with other fields
                print(f"Warning: Transform failed for {bbf_field}: {e}")
                bbf_record[bbf_field] = None

    return bbf_record
