#!/usr/bin/env python3
"""
Auto-generated transformation functions for ES Off_Net__c to BBF Off_Net__c migration.

Generated by: transformation-generator agent
Date: 2026-01-15T17:10:04.504435
Source: ES_Off_Net__c_to_BBF_Off_Net__c_mapping.xlsx

Usage:
    from transformers.off_net_transformers import TRANSFORMERS, apply_transformers

    # Apply single transformer
    bbf_value = TRANSFORMERS['Aloc_COGS_Provider__c'](es_record['Off_Net_Vendor__c'])

    # Apply all transformers
    bbf_record = apply_transformers(es_record)
"""

import re
from typing import Any, Optional
from datetime import datetime, date


# Picklist value mappings
TERM_MAP = {
    '6': '36',
    '12': '12',
    '18': '1',
    '24': '24',
    '36': '36',
    '48': '48',
    '60': '60',
    '62': '62',
    '84': '84',
    '96': '96',
    '120': '120',
    '240': '240',
    'NO': 'Not Renewing',
    'MO': 'MO'
}

PRODUCT_MAP = {
    '5 Mb': '5 Mbps',
    '10 Mb': '10 Mbps',
    '20 Mb': '20 Mbps',
    '30 Mb': '30 Mb',
    '40 Mb': '40 Mb',
    '50 Mb': '250 Mbps',
    '60 Mb': '60 Mb',
    '70 Mb': '70 Mb',
    '80 Mb': '80 Mb',
    '90 Mb': '90 Mb',
    '100 Mb': '100 Mbps',
    '150 Mb': '150 Mb',
    '200 Mb': '200 Mbps',
    '250 Mb': '250 Mbps',
    '300 Mb': '300 Mbps',
    '400 Mb': '400 Mbps',
    '500 Mb': '500 Mbps',
    '600 Mb': '600 Mbps',
    '700 Mb': '700 Mbps',
    '800 Mb': '800 Mbps',
    '900 Mb': '900 Mbps',
    '1 Gb': '1 GB DIA',
    '2 Gb': '2 Gbps',
    '2.5 Gb': '2.5 Gb',
    '5 Gb': '25 Gbps',
    '10 Gb': '10 Gbps',
    '40 Gb': '40 Gbps',
    '100 Gb': '100 Gbps',
    'DSL': 'CRDSLA1',
    'DS0': 'Cross Connect - DS0',
    'DS1': 'Cross Connect - DS1',
    'DS3': 'Cross Connect - DS3',
    'OC3': 'OC3',
    'OC12': 'OC12',
    'OC48': 'OC48',
    'OC192': 'OC192',
    'Cable': 'Cable',
    'Collocation': 'COLLO',
    'Cross Connect': 'Cross Connect',
    'Dark Fiber': 'Dark Fiber',
    'Voice': 'Voice Trunk',
    'Wireless': 'Wireless',
    'Tower Rent': 'Tower Rent'
}

SERVICE_TYPE_MAP = {
    'Circuit': 'Electrical Circuit',
    'Cross Connect': 'Cross Connect',
    'Collocation': 'Collocation'
}

OFF_NET_PROBLEM_REASON_CODE_MAP = {
    'Customer Readiness': 'Customer Readiness',
    'Pending MSA/Contract': 'Pending MSA/Contract',
    'Related Order Dependency': 'Related Order Dependency',
    'Pending ETL Approval': 'Pending ETL Approval',
    'Pending Migration': 'Pending Migration',
    'Approved for Future Date': 'Approved for Future Date',
    'Requires Research': 'Requires Research'
}

OFF_NET_SERVICE_STATUS_MAP = {
    'Pending': 'Pending',
    'Active': 'Active',
    'NOC Review': 'NOC Review',
    'Soft Disco': 'Soft Disco',
    'Pending Disco': 'Pending Disco',
    'Invoice Evaluation': 'Invoice Evaluation',
    'Disco': 'Disco'
}


def transform_aloc_cogs_provider(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Off_Net_Vendor__c to BBF Aloc_COGS_Provider__c.

    ES Field: Off_Net_Vendor__c (Last Mile Carrier)
    ES Type: reference

    BBF Field: Aloc_COGS_Provider__c (Aloc COGS Provider)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    A-Location COGS provider (reference vs text mismatch) | Data type conversion required

    Args:
        es_value: The source value from ES Off_Net_Vendor__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Aloc_COGS_Provider__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_term(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Term__c to BBF Term__c.

    ES Field: Term__c (Term)
    ES Type: picklist

    BBF Field: Term__c (Term)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Contract term in months (requires picklist value mapping) | Picklist value mapping required

    Args:
        es_value: The source value from ES Term__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Term__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return TERM_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_zloc_cogs_provider(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Vendor_Name__c to BBF Zloc_COGS_Provider__c.

    ES Field: Vendor_Name__c (Accounts Payable Vendor)
    ES Type: reference

    BBF Field: Zloc_COGS_Provider__c (Zloc COGS Provider)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Z-Location COGS provider (reference vs text, accounts payable vendor) | Data type conversion required

    Args:
        es_value: The source value from ES Vendor_Name__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Zloc_COGS_Provider__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_product(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Bandwidth__c to BBF Product__c.

    ES Field: Bandwidth__c (Bandwidth)
    ES Type: picklist

    BBF Field: Product__c (Product)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Large BBF product picklist (471 values) vs ES bandwidth picklist (43 values) | Picklist value mapping required

    Args:
        es_value: The source value from ES Bandwidth__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Product__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return PRODUCT_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_service_type(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Off_Net_Type__c to BBF Service_Type__c.

    ES Field: Off_Net_Type__c (Off Net Type)
    ES Type: multipicklist

    BBF Field: Service_Type__c (Service Type)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Service type picklist (72 values) vs off-net type multipicklist (3 values) | Data type conversion required

    Args:
        es_value: The source value from ES Off_Net_Type__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Service_Type__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return SERVICE_TYPE_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_bbf_circuit_id(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Internal_Circuit_Id__c to BBF BBF_Circuit_ID__c.

    ES Field: Internal_Circuit_Id__c (Internal Circuit Id)
    ES Type: textarea

    BBF Field: BBF_Circuit_ID__c (BBF Circuit ID)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    BBF circuit ID (textarea truncation needed) | Data type conversion required

    Args:
        es_value: The source value from ES Internal_Circuit_Id__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF BBF_Circuit_ID__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_demarc_location(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Demarc_Loaction__c to BBF Demarc_Location__c.

    ES Field: Demarc_Loaction__c (Demarc Loaction)
    ES Type: textarea

    BBF Field: Demarc_Location__c (Demarc Location)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Demarc location (typo in ES field, requires truncation) | Data type conversion required

    Args:
        es_value: The source value from ES Demarc_Loaction__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Demarc_Location__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_off_net_service_status(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES LEC_Order_Status__c to BBF Off_Net_Service_Status__c.

    ES Field: LEC_Order_Status__c (LEC Order Status)
    ES Type: picklist

    BBF Field: Off_Net_Service_Status__c (Off-Net Service Status)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Service status picklist (requires value mapping, different labels) | Picklist value mapping required

    Args:
        es_value: The source value from ES LEC_Order_Status__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Off_Net_Service_Status__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return OFF_NET_SERVICE_STATUS_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_stripped_circuit_id(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Stripped_Circuit_ID2__c to BBF Stripped_Circuit_ID__c.

    ES Field: Stripped_Circuit_ID2__c (Stripped Circuit ID)
    ES Type: textarea

    BBF Field: Stripped_Circuit_ID__c (Stripped Circuit ID)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Stripped circuit ID (different field purposes) | Data type conversion required

    Args:
        es_value: The source value from ES Stripped_Circuit_ID2__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Stripped_Circuit_ID__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_vendor_ban(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Vendor_Ban__c to BBF Vendor_BAN__c.

    ES Field: Vendor_Ban__c (Vendor Ban)
    ES Type: reference

    BBF Field: Vendor_BAN__c (Vendor BAN)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Vendor billing account number reference (exact match) | Data type conversion required

    Args:
        es_value: The source value from ES Vendor_Ban__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Vendor_BAN__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_vendor_nni(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Vendor_NNI__c to BBF Vendor_NNI__c.

    ES Field: Vendor_NNI__c (Vendor NNI)
    ES Type: reference

    BBF Field: Vendor_NNI__c (Vendor NNI)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Vendor NNI reference vs text (type mismatch) | Data type conversion required

    Args:
        es_value: The source value from ES Vendor_NNI__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Vendor_NNI__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_vendor_pon(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES VendorPON__c to BBF Vendor_PON__c.

    ES Field: VendorPON__c (Vendor PON #)
    ES Type: textarea

    BBF Field: Vendor_PON__c (Vendor PON)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Vendor purchase order number (exact match) | Data type conversion required

    Args:
        es_value: The source value from ES VendorPON__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Vendor_PON__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


# Transformer registry
TRANSFORMERS = {
    'Aloc_COGS_Provider__c': transform_aloc_cogs_provider,
    'Term__c': transform_term,
    'Zloc_COGS_Provider__c': transform_zloc_cogs_provider,
    'Product__c': transform_product,
    'Service_Type__c': transform_service_type,
    'BBF_Circuit_ID__c': transform_bbf_circuit_id,
    'Demarc_Location__c': transform_demarc_location,
    'Off_Net_Service_Status__c': transform_off_net_service_status,
    'Stripped_Circuit_ID__c': transform_stripped_circuit_id,
    'Vendor_BAN__c': transform_vendor_ban,
    'Vendor_NNI__c': transform_vendor_nni,
    'Vendor_PON__c': transform_vendor_pon
}

# Field mapping (BBF -> ES)
FIELD_MAPPING = {
    'Aloc_COGS_Provider__c': 'Off_Net_Vendor__c',
    'Term__c': 'Term__c',
    'Zloc_COGS_Provider__c': 'Vendor_Name__c',
    'Product__c': 'Bandwidth__c',
    'Service_Type__c': 'Off_Net_Type__c',
    'BBF_Circuit_ID__c': 'Internal_Circuit_Id__c',
    'Demarc_Location__c': 'Demarc_Loaction__c',
    'Off_Net_Service_Status__c': 'LEC_Order_Status__c',
    'Stripped_Circuit_ID__c': 'Stripped_Circuit_ID2__c',
    'Vendor_BAN__c': 'Vendor_Ban__c',
    'Vendor_NNI__c': 'Vendor_NNI__c',
    'Vendor_PON__c': 'VendorPON__c'
}


def apply_transformers(es_record: dict) -> dict:
    """
    Apply all transformers to an ES record.

    Args:
        es_record: Dictionary of ES field values (field API name -> value)

    Returns:
        Dictionary of transformed BBF field values (BBF field API name -> value)
    """
    bbf_record = {}

    for bbf_field, transformer in TRANSFORMERS.items():
        es_field = FIELD_MAPPING.get(bbf_field)
        if es_field and es_field in es_record:
            try:
                bbf_record[bbf_field] = transformer(es_record[es_field], es_record)
            except Exception as e:
                # Log error but continue with other fields
                print(f"Warning: Transform failed for {bbf_field}: {e}")
                bbf_record[bbf_field] = None

    return bbf_record
