#!/usr/bin/env python3
"""
Auto-generated transformation functions for ES Order to BBF Service__c migration.

Generated by: transformation-generator agent
Date: 2026-01-15T17:10:04.595468
Source: ES_Order_to_BBF_Service__c_mapping.xlsx

Usage:
    from transformers.service_transformers import TRANSFORMERS, apply_transformers

    # Apply single transformer
    bbf_value = TRANSFORMERS['Circuit_Capacity__c'](es_record['Service_Provided__c'])

    # Apply all transformers
    bbf_record = apply_transformers(es_record)
"""

import re
from typing import Any, Optional
from datetime import datetime, date


# Picklist value mappings
CHANGE_TYPE_MAP = {
    'Activated': 'No Change',
    'Suspended (Late Payment)': 'No Change',
    'Disconnect in Progress': 'Disconnect'
}

OPPORTUNITY_TYPE_MAP = {
    'New': 'New Order',
    'Change': 'Change',
    'Renewal': 'Renewal',
    'Upgrade': 'Upgrade',
    'Downgrade': 'Downgrade',
    'Move': 'Move'
}

DISCONNECT_REASON_CODES_MAP = {
    'Price': 'Price Increase',
    'Customer out of business': 'Closing/Going out of Business/Moving Location',
    'Non-Payment': 'Non-payment/Financial Difficulty',
    'Service Replaced with Different ES Product': 'Replaced by New BBF Circuit',
    'Dissatisfied with Everstream': 'Dissatisfied with Service',
    'Service No Longer Needed': 'Service no longer required',
    'Unknown': 'Undisclosed',
    'Change in Existing Service': 'Replaced by New BBF Circuit',
    'Wholesale Customer': 'Wholesale Customer',
    'Portability/Revenue Replacement': 'Replaced by New BBF Circuit',
    'Other': 'Undisclosed'
}

SERVICE_ACCESS_BUILD_MAP = {
    'On-Net Lit': 'On-Net Lit',
    'On-Net New': 'On-Net New',
    'Off-Net': 'Off-Net'
}


def transform_circuit_capacity(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Service_Provided__c to BBF Circuit_Capacity__c.

    ES Field: Service_Provided__c (Service Bandwidth (Highst Mbps))
    ES Type: double

    BBF Field: Circuit_Capacity__c (Circuit Capacity COPS)
    BBF Type: string(255)
    BBF Required: No

    AI Reasoning:
    Service_Provided__c contains bandwidth in Mbps (numeric), needs conversion to Circuit_Capacity__c string format

    Args:
        es_value: The source value from ES Service_Provided__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Circuit_Capacity__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Convert number to string
    if es_value is None:
        return ''
    return str(es_value)


def transform_active_date(es_value: Any, context: dict = None) -> Optional[date]:
    """
    Transform ES ActivatedDate to BBF Active_Date__c.

    ES Field: ActivatedDate (Activated Date)
    ES Type: datetime

    BBF Field: Active_Date__c (Active Date)
    BBF Type: date
    BBF Required: No

    AI Reasoning:
    ActivatedDate (datetime) needs conversion to Active_Date__c (date only)

    Args:
        es_value: The source value from ES ActivatedDate
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Active_Date__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Convert datetime to date
    if isinstance(es_value, datetime):
        return es_value.date()
    elif isinstance(es_value, date):
        return es_value
    elif isinstance(es_value, str):
        try:
            parsed = datetime.fromisoformat(es_value.replace('Z', '+00:00'))
            return parsed.date()
        except (ValueError, AttributeError):
            return None
    return None


def transform_a_node(es_value: Any, context: dict = None) -> Optional[Any]:
    """
    Transform ES Node__c to BBF A_Node__c.

    ES Field: Node__c (Node)
    ES Type: reference

    BBF Field: A_Node__c (A Node)
    BBF Type: reference
    BBF Required: No

    AI Reasoning:
    ES has single Node__c field, BBF has A_Node and Z_Node - may need business logic to determine A vs Z

    Args:
        es_value: The source value from ES Node__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF A_Node__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_z_node(es_value: Any, context: dict = None) -> Optional[Any]:
    """
    Transform ES Ring__c to BBF Z_Node__c.

    ES Field: Ring__c (Ring)
    ES Type: reference

    BBF Field: Z_Node__c (Z Node)
    BBF Type: reference
    BBF Required: No

    AI Reasoning:
    Ring topology reference - may relate to Z Node in BBF architecture, needs validation

    Args:
        es_value: The source value from ES Ring__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Z_Node__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_pon(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES PON__c to BBF PON__c.

    ES Field: PON__c (PON)
    ES Type: textarea(255)

    BBF Field: PON__c (PON)
    BBF Type: string(100)
    BBF Required: No

    AI Reasoning:
    PON (Purchase Order Number) - field types differ (textarea vs string), may need truncation

    Args:
        es_value: The source value from ES PON__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF PON__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_secondary_circuit_id(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Order_Link__c to BBF Secondary_Circuit_Id__c.

    ES Field: Order_Link__c (Order Link)
    ES Type: string(1300)

    BBF Field: Secondary_Circuit_Id__c (Secondary Circuit ID COPS)
    BBF Type: string(255)
    BBF Required: No

    AI Reasoning:
    Order_Link__c may contain URL/reference to secondary order - needs parsing to extract circuit ID

    Args:
        es_value: The source value from ES Order_Link__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Secondary_Circuit_Id__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_bandwidth(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Service_Provided__c to BBF Bandwidth__c.

    ES Field: Service_Provided__c (Service Bandwidth (Highst Mbps))
    ES Type: double

    BBF Field: Bandwidth__c (Bandwidth)
    BBF Type: string(255)
    BBF Required: No

    AI Reasoning:
    Duplicate of Circuit_Capacity__c - Service_Provided__c numeric needs string conversion with units

    Args:
        es_value: The source value from ES Service_Provided__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Bandwidth__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Convert number to string
    if es_value is None:
        return ''
    return str(es_value)


def transform_change_type(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Order_Type_Data_Load__c to BBF Change_Type__c.

    ES Field: Order_Type_Data_Load__c (Order Type)
    ES Type: multipicklist

    BBF Field: Change_Type__c (Change Type)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Order_Type_Data_Load__c is multipicklist (New, Change, Renewal, etc.), BBF Change_Type__c is single picklist - needs logic to select primary type

    Args:
        es_value: The source value from ES Order_Type_Data_Load__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Change_Type__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return CHANGE_TYPE_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_carrier_code(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Last_Mile_Carrier__c to BBF Carrier_Code__c.

    ES Field: Last_Mile_Carrier__c (Last Mile Carrier)
    ES Type: reference

    BBF Field: Carrier_Code__c (ZNodeID Carrier Code COPS)
    BBF Type: string(255)
    BBF Required: No

    AI Reasoning:
    Last_Mile_Carrier__c is reference to carrier account - needs to extract carrier code/name for BBF string field

    Args:
        es_value: The source value from ES Last_Mile_Carrier__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Carrier_Code__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_service_access_build(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Build_Type_Address_Z__c to BBF Service_Access_Build__c.

    ES Field: Build_Type_Address_Z__c (Build Type: Address Z)
    ES Type: picklist

    BBF Field: Service_Access_Build__c (Service Access Build)
    BBF Type: string(50)
    BBF Required: No

    AI Reasoning:
    Build_Type_Address_Z__c indicates On-Net Lit/New or Off-Net - maps to service access build type in BBF

    Args:
        es_value: The source value from ES Build_Type_Address_Z__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Service_Access_Build__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_account_manager(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Sales_Rep__c to BBF Account_Manager__c.

    ES Field: Sales_Rep__c (Sales Rep)
    ES Type: reference

    BBF Field: Account_Manager__c (Account Manager COPS)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    Sales_Rep__c reference needs to extract user name for Account_Manager__c text field

    Args:
        es_value: The source value from ES Sales_Rep__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Account_Manager__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_disconnect_reason(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES End_Reason_Notes__c to BBF Disconnect_Reason__c.

    ES Field: End_Reason_Notes__c (End Reason Notes)
    ES Type: textarea(8000)

    BBF Field: Disconnect_Reason__c (Disconnect Reason Notes)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    End_Reason_Notes__c provides disconnect reason details - may need truncation from 8000 to 255 chars

    Args:
        es_value: The source value from ES End_Reason_Notes__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Disconnect_Reason__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_engineer(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Service_Delivery_Manager__c to BBF Engineer__c.

    ES Field: Service_Delivery_Manager__c (Service Delivery Specialist)
    ES Type: reference

    BBF Field: Engineer__c (Engineer COPS)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    Service_Delivery_Manager__c reference needs name extraction for Engineer__c text field

    Args:
        es_value: The source value from ES Service_Delivery_Manager__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Engineer__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_osp_engineer(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES OSP_Engineer__c to BBF OSP_Engineer__c.

    ES Field: OSP_Engineer__c (Address Z OSP Engineer)
    ES Type: reference

    BBF Field: OSP_Engineer__c (OSP Engineer COPS)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    OSP_Engineer__c reference needs name extraction for BBF text field

    Args:
        es_value: The source value from ES OSP_Engineer__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF OSP_Engineer__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_order_received_by(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES CreatedById to BBF Order_Received_By__c.

    ES Field: CreatedById (Created By ID)
    ES Type: reference

    BBF Field: Order_Received_By__c (Order Received By COPS)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    CreatedById is user who created order - needs name lookup for Order_Received_By__c text

    Args:
        es_value: The source value from ES CreatedById
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Order_Received_By__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_order_received_date(es_value: Any, context: dict = None) -> Optional[date]:
    """
    Transform ES CreatedDate to BBF Order_Received_Date__c.

    ES Field: CreatedDate (Created Date)
    ES Type: datetime

    BBF Field: Order_Received_Date__c (Order Received Date)
    BBF Type: date
    BBF Required: No

    AI Reasoning:
    CreatedDate datetime needs conversion to Order_Received_Date__c date only

    Args:
        es_value: The source value from ES CreatedDate
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Order_Received_Date__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Convert datetime to date
    if isinstance(es_value, datetime):
        return es_value.date()
    elif isinstance(es_value, date):
        return es_value
    elif isinstance(es_value, str):
        try:
            parsed = datetime.fromisoformat(es_value.replace('Z', '+00:00'))
            return parsed.date()
        except (ValueError, AttributeError):
            return None
    return None


def transform_outside_plant_required(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES OSP_Needed__c to BBF Outside_Plant_Required__c.

    ES Field: OSP_Needed__c (OSP Needed)
    ES Type: boolean

    BBF Field: Outside_Plant_Required__c (Outside Plant Required)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    OSP_Needed__c boolean needs conversion to text 'Yes/No' for Outside_Plant_Required__c

    Args:
        es_value: The source value from ES OSP_Needed__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Outside_Plant_Required__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_opportunity_type(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Service_Category_Multi__c to BBF Opportunity_Type__c.

    ES Field: Service_Category_Multi__c (Service Category Multi (Deprecated))
    ES Type: multipicklist

    BBF Field: Opportunity_Type__c (Last Opportunity Type)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Service_Category_Multi__c multipicklist needs conversion to single Opportunity_Type__c picklist value

    Args:
        es_value: The source value from ES Service_Category_Multi__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Opportunity_Type__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return OPPORTUNITY_TYPE_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_provisioned_by(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Initially_Activated_By__c to BBF Provisioned_By__c.

    ES Field: Initially_Activated_By__c (Initially Activated By)
    ES Type: reference

    BBF Field: Provisioned_By__c (Provisioned By COPS)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    Initially_Activated_By__c user reference needs name extraction for Provisioned_By__c text

    Args:
        es_value: The source value from ES Initially_Activated_By__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Provisioned_By__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_replaced_by_ckt_code(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Service_Order_Details_Replacing__c to BBF Replaced_By_Ckt_Code__c.

    ES Field: Service_Order_Details_Replacing__c (Service Order Details (Replacing))
    ES Type: string(1300)

    BBF Field: Replaced_By_Ckt_Code__c (Replaced By CKT Code)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    Service_Order_Details_Replacing__c contains details of replacement order - needs parsing for circuit code

    Args:
        es_value: The source value from ES Service_Order_Details_Replacing__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Replaced_By_Ckt_Code__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_replacing_ckt_code(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Service_Order_Agreement_Replacing__c to BBF Replacing_Ckt_Code__c.

    ES Field: Service_Order_Agreement_Replacing__c (Service Order Agreement (Replacing))
    ES Type: reference

    BBF Field: Replacing_Ckt_Code__c (Replacing CKT Code)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    Service_Order_Agreement_Replacing__c reference to order being replaced - needs OrderNumber lookup

    Args:
        es_value: The source value from ES Service_Order_Agreement_Replacing__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Replacing_Ckt_Code__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_sales_engineer(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Sales_Rep__c to BBF Sales_Engineer__c.

    ES Field: Sales_Rep__c (Sales Rep)
    ES Type: reference

    BBF Field: Sales_Engineer__c (Sales Engineer COPS)
    BBF Type: textarea(255)
    BBF Required: No

    AI Reasoning:
    Sales_Rep__c user reference - extract name for Sales_Engineer__c text field

    Args:
        es_value: The source value from ES Sales_Rep__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Sales_Engineer__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_signal_type(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Primary_Product_Family__c to BBF Signal_Type__c.

    ES Field: Primary_Product_Family__c (Primary Product Family)
    ES Type: string(1300)

    BBF Field: Signal_Type__c (Signal Type)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Primary_Product_Family__c may indicate if Voice/Data/Video - needs parsing to map to Signal_Type__c picklist

    Args:
        es_value: The source value from ES Primary_Product_Family__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Signal_Type__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_aloc_cogs_provider(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Last_Mile_Carrier__c to BBF Aloc_COGS_Provider__c.

    ES Field: Last_Mile_Carrier__c (Last Mile Carrier)
    ES Type: reference

    BBF Field: Aloc_COGS_Provider__c (Aloc COGS Provider)
    BBF Type: string(255)
    BBF Required: No

    AI Reasoning:
    Last_Mile_Carrier__c reference - extract carrier name for A location COGS provider

    Args:
        es_value: The source value from ES Last_Mile_Carrier__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Aloc_COGS_Provider__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_zloc_cogs_provider(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Last_Mile_Carrier__c to BBF Zloc_COGS_Provider__c.

    ES Field: Last_Mile_Carrier__c (Last Mile Carrier)
    ES Type: reference

    BBF Field: Zloc_COGS_Provider__c (Zloc COGS Provider)
    BBF Type: string(255)
    BBF Required: No

    AI Reasoning:
    Last_Mile_Carrier__c reference - extract carrier name for Z location COGS provider (may be different if diverse)

    Args:
        es_value: The source value from ES Last_Mile_Carrier__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Zloc_COGS_Provider__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_disconnect_reason_codes(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Service_End_Reasons__c to BBF Disconnect_Reason_Codes__c.

    ES Field: Service_End_Reasons__c (Service End Reason)
    ES Type: picklist

    BBF Field: Disconnect_Reason_Codes__c (Disconnect Reason)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Service_End_Reasons__c picklist values need mapping to BBF Disconnect_Reason_Codes__c values

    Args:
        es_value: The source value from ES Service_End_Reasons__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Disconnect_Reason_Codes__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return DISCONNECT_REASON_CODES_MAP.get(es_str, es_str)  # Return original if no mapping


# Transformer registry
TRANSFORMERS = {
    'Circuit_Capacity__c': transform_circuit_capacity,
    'Active_Date__c': transform_active_date,
    'A_Node__c': transform_a_node,
    'Z_Node__c': transform_z_node,
    'PON__c': transform_pon,
    'Secondary_Circuit_Id__c': transform_secondary_circuit_id,
    'Bandwidth__c': transform_bandwidth,
    'Change_Type__c': transform_change_type,
    'Carrier_Code__c': transform_carrier_code,
    'Service_Access_Build__c': transform_service_access_build,
    'Account_Manager__c': transform_account_manager,
    'Disconnect_Reason__c': transform_disconnect_reason,
    'Engineer__c': transform_engineer,
    'OSP_Engineer__c': transform_osp_engineer,
    'Order_Received_By__c': transform_order_received_by,
    'Order_Received_Date__c': transform_order_received_date,
    'Outside_Plant_Required__c': transform_outside_plant_required,
    'Opportunity_Type__c': transform_opportunity_type,
    'Provisioned_By__c': transform_provisioned_by,
    'Replaced_By_Ckt_Code__c': transform_replaced_by_ckt_code,
    'Replacing_Ckt_Code__c': transform_replacing_ckt_code,
    'Sales_Engineer__c': transform_sales_engineer,
    'Signal_Type__c': transform_signal_type,
    'Aloc_COGS_Provider__c': transform_aloc_cogs_provider,
    'Zloc_COGS_Provider__c': transform_zloc_cogs_provider,
    'Disconnect_Reason_Codes__c': transform_disconnect_reason_codes
}

# Field mapping (BBF -> ES)
FIELD_MAPPING = {
    'Circuit_Capacity__c': 'Service_Provided__c',
    'Active_Date__c': 'ActivatedDate',
    'A_Node__c': 'Node__c',
    'Z_Node__c': 'Ring__c',
    'PON__c': 'PON__c',
    'Secondary_Circuit_Id__c': 'Order_Link__c',
    'Bandwidth__c': 'Service_Provided__c',
    'Change_Type__c': 'Order_Type_Data_Load__c',
    'Carrier_Code__c': 'Last_Mile_Carrier__c',
    'Service_Access_Build__c': 'Build_Type_Address_Z__c',
    'Account_Manager__c': 'Sales_Rep__c',
    'Disconnect_Reason__c': 'End_Reason_Notes__c',
    'Engineer__c': 'Service_Delivery_Manager__c',
    'OSP_Engineer__c': 'OSP_Engineer__c',
    'Order_Received_By__c': 'CreatedById',
    'Order_Received_Date__c': 'CreatedDate',
    'Outside_Plant_Required__c': 'OSP_Needed__c',
    'Opportunity_Type__c': 'Service_Category_Multi__c',
    'Provisioned_By__c': 'Initially_Activated_By__c',
    'Replaced_By_Ckt_Code__c': 'Service_Order_Details_Replacing__c',
    'Replacing_Ckt_Code__c': 'Service_Order_Agreement_Replacing__c',
    'Sales_Engineer__c': 'Sales_Rep__c',
    'Signal_Type__c': 'Primary_Product_Family__c',
    'Aloc_COGS_Provider__c': 'Last_Mile_Carrier__c',
    'Zloc_COGS_Provider__c': 'Last_Mile_Carrier__c',
    'Disconnect_Reason_Codes__c': 'Service_End_Reasons__c'
}


def apply_transformers(es_record: dict) -> dict:
    """
    Apply all transformers to an ES record.

    Args:
        es_record: Dictionary of ES field values (field API name -> value)

    Returns:
        Dictionary of transformed BBF field values (BBF field API name -> value)
    """
    bbf_record = {}

    for bbf_field, transformer in TRANSFORMERS.items():
        es_field = FIELD_MAPPING.get(bbf_field)
        if es_field and es_field in es_record:
            try:
                bbf_record[bbf_field] = transformer(es_record[es_field], es_record)
            except Exception as e:
                # Log error but continue with other fields
                print(f"Warning: Transform failed for {bbf_field}: {e}")
                bbf_record[bbf_field] = None

    return bbf_record
