#!/usr/bin/env python3
"""
Auto-generated transformation functions for ES OrderItem to BBF Service_Charge__c migration.

Generated by: transformation-generator agent
Date: 2026-01-15T17:10:04.547038
Source: ES_OrderItem_to_BBF_Service_Charge__c_mapping.xlsx

Usage:
    from transformers.service_charge_transformers import TRANSFORMERS, apply_transformers

    # Apply single transformer
    bbf_value = TRANSFORMERS['Description__c'](es_record['Description'])

    # Apply all transformers
    bbf_record = apply_transformers(es_record)
"""

import re
from typing import Any, Optional
from datetime import datetime, date


# Picklist value mappings
CHARGE_CLASS_MAP = {
    'One-Time': 'One-Time',
    'Recurring': 'RECUR',
    'Usage': 'Usage'
}

BILL_SCHEDULE_TYPE_MAP = {
    'Monthly': 'Monthly',
    'Quarterly': 'Quarterly',
    'Semiannual': 'Semiannual',
    'Annual': 'Annual',
    'Invoice Plan': 'Invoice Plan'
}


def transform_description(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Description to BBF Description__c.

    ES Field: Description (Line Description)
    ES Type: string

    BBF Field: Description__c (Description)
    BBF Type: textarea
    BBF Required: No

    AI Reasoning:
    Charge description - maps to OrderItem Description or Item_Summary__c

    Args:
        es_value: The source value from ES Description
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Description__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_sequence(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES OrderItemNumber to BBF Sequence__c.

    ES Field: OrderItemNumber (Order Product Number)
    ES Type: string

    BBF Field: Sequence__c (Sequence)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Sequence or line number - maps to OrderItemNumber

    Args:
        es_value: The source value from ES OrderItemNumber
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Sequence__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_amount(es_value: Any, context: dict = None) -> Optional[float]:
    """
    Transform ES Total_MRC_Amortized__c to BBF Amount__c.

    ES Field: Total_MRC_Amortized__c (Total MRC)
    ES Type: currency

    BBF Field: Amount__c (MRC)
    BBF Type: currency
    BBF Required: No

    AI Reasoning:
    MRC amount (calculated as Unit_Rate__c * Units__c) - maps to Total_MRC_Amortized__c

    Args:
        es_value: The source value from ES Total_MRC_Amortized__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Amount__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_pricebookentryid(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES PricebookEntryId to BBF PricebookEntryId__c.

    ES Field: PricebookEntryId (Price Book Entry ID)
    ES Type: reference

    BBF Field: PricebookEntryId__c ((dep) PricebookEntryId)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Pricebook entry reference - direct match to OrderItem.PricebookEntryId

    Args:
        es_value: The source value from ES PricebookEntryId
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF PricebookEntryId__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_charge_class(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES SBQQ__ChargeType__c to BBF Charge_Class__c.

    ES Field: SBQQ__ChargeType__c (Charge Type)
    ES Type: picklist

    BBF Field: Charge_Class__c (Charge Class)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Charge classification (RECUR/NONRECUR) - derive from SBQQ__ChargeType__c (Recurring=RECUR, One-Time=NONRECUR)

    Args:
        es_value: The source value from ES SBQQ__ChargeType__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Charge_Class__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return CHARGE_CLASS_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_charge_active(es_value: Any, context: dict = None) -> Optional[bool]:
    """
    Transform ES SBQQ__Activated__c to BBF Charge_Active__c.

    ES Field: SBQQ__Activated__c (Activated)
    ES Type: boolean

    BBF Field: Charge_Active__c (Charge Active)
    BBF Type: boolean
    BBF Required: Yes

    AI Reasoning:
    Whether charge is active - derive from SBQQ__Activated__c and !Cancelled__c

    Args:
        es_value: The source value from ES SBQQ__Activated__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Charge_Active__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return False

    # Convert to boolean
    if es_value is None:
        return False
    if isinstance(es_value, bool):
        return es_value
    if isinstance(es_value, str):
        return es_value.lower() in ('true', 'yes', '1', 'y')
    return bool(es_value)


def transform_product_category(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Product_Family__c to BBF Product_Category__c.

    ES Field: Product_Family__c (Product Family)
    ES Type: string

    BBF Field: Product_Category__c ((dep) Product Category)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Deprecated product category (formula) - may derive from Product_Family__c

    Args:
        es_value: The source value from ES Product_Family__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Product_Category__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_product_name(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Product_Name__c to BBF Product_Name__c.

    ES Field: Product_Name__c (Product Name)
    ES Type: string

    BBF Field: Product_Name__c ((dep) Product Name)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Deprecated product name (formula) - direct match if needed

    Args:
        es_value: The source value from ES Product_Name__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Product_Name__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_product(es_value: Any, context: dict = None) -> Optional[Any]:
    """
    Transform ES Product2Id to BBF Product__c.

    ES Field: Product2Id (Product ID)
    ES Type: reference

    BBF Field: Product__c ((dep) Product)
    BBF Type: reference
    BBF Required: No

    AI Reasoning:
    Deprecated product reference - maps to Product2Id

    Args:
        es_value: The source value from ES Product2Id
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Product__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_bill_schedule_type(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES SBQQ__BillingFrequency__c to BBF Bill_Schedule_Type__c.

    ES Field: SBQQ__BillingFrequency__c (Billing Frequency)
    ES Type: picklist

    BBF Field: Bill_Schedule_Type__c (Bill Schedule Type)
    BBF Type: picklist
    BBF Required: No

    AI Reasoning:
    Billing schedule type - derive from SBQQ__BillingFrequency__c

    Args:
        es_value: The source value from ES SBQQ__BillingFrequency__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Bill_Schedule_Type__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Map picklist values using lookup dictionary
    if es_value is None:
        return None
    es_str = str(es_value).strip()
    return BILL_SCHEDULE_TYPE_MAP.get(es_str, es_str)  # Return original if no mapping


def transform_service_order_line_charge(es_value: Any, context: dict = None) -> Optional[Any]:
    """
    Transform ES SBQQ__QuoteLine__c to BBF Service_Order_Line_Charge__c.

    ES Field: SBQQ__QuoteLine__c (Quote Line)
    ES Type: reference

    BBF Field: Service_Order_Line_Charge__c (Service Order Line Charge)
    BBF Type: reference
    BBF Required: No

    AI Reasoning:
    Reference to originating quote line - may map to SBQQ__QuoteLine__c if needed

    Args:
        es_value: The source value from ES SBQQ__QuoteLine__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Service_Order_Line_Charge__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_mrc_net(es_value: Any, context: dict = None) -> Optional[float]:
    """
    Transform ES Total_MRC_Amortized__c to BBF MRC_Net__c.

    ES Field: Total_MRC_Amortized__c (Total MRC)
    ES Type: currency

    BBF Field: MRC_Net__c (MRC Net)
    BBF Type: currency
    BBF Required: No

    AI Reasoning:
    Net MRC (formula field) - calculate from OrderItem pricing

    Args:
        es_value: The source value from ES Total_MRC_Amortized__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF MRC_Net__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_nrc_net(es_value: Any, context: dict = None) -> Optional[float]:
    """
    Transform ES NRC_Non_Amortized__c to BBF NRC_Net__c.

    ES Field: NRC_Non_Amortized__c (NRC (Non-Amortized))
    ES Type: currency

    BBF Field: NRC_Net__c (NRC Net)
    BBF Type: currency
    BBF Required: No

    AI Reasoning:
    Net NRC (formula field) - calculate from OrderItem NRC fields

    Args:
        es_value: The source value from ES NRC_Non_Amortized__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF NRC_Net__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_active(es_value: Any, context: dict = None) -> Optional[bool]:
    """
    Transform ES SBQQ__Activated__c to BBF Active__c.

    ES Field: SBQQ__Activated__c (Activated)
    ES Type: boolean

    BBF Field: Active__c (Active)
    BBF Type: boolean
    BBF Required: Yes

    AI Reasoning:
    Active status (formula field) - derive from SBQQ__Activated__c and !Cancelled__c

    Args:
        es_value: The source value from ES SBQQ__Activated__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Active__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return False

    # Convert to boolean
    if es_value is None:
        return False
    if isinstance(es_value, bool):
        return es_value
    if isinstance(es_value, str):
        return es_value.lower() in ('true', 'yes', '1', 'y')
    return bool(es_value)


def transform_start_date_achieved_on(es_value: Any, context: dict = None) -> Optional[date]:
    """
    Transform ES ServiceDate to BBF Start_Date_Achieved_On__c.

    ES Field: ServiceDate (Start Date)
    ES Type: date

    BBF Field: Start_Date_Achieved_On__c (Start Date Achieved On)
    BBF Type: date
    BBF Required: No

    AI Reasoning:
    Date when start date was achieved - may track when ServiceDate was set

    Args:
        es_value: The source value from ES ServiceDate
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Start_Date_Achieved_On__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_end_date_achieved_on(es_value: Any, context: dict = None) -> Optional[date]:
    """
    Transform ES EndDate to BBF End_Date_Achieved_On__c.

    ES Field: EndDate (End Date)
    ES Type: date

    BBF Field: End_Date_Achieved_On__c (End Date Achieved On)
    BBF Type: date
    BBF Required: No

    AI Reasoning:
    Date when end date was achieved - may track when EndDate was set

    Args:
        es_value: The source value from ES EndDate
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF End_Date_Achieved_On__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_aloc_cogs_provider(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Last_Mile_Carrier__c to BBF Aloc_COGS_Provider__c.

    ES Field: Last_Mile_Carrier__c (Last Mile Carrier)
    ES Type: reference

    BBF Field: Aloc_COGS_Provider__c (Aloc COGS Provider)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    A-location COGS provider - may derive from Last_Mile_Carrier__c if location-specific

    Args:
        es_value: The source value from ES Last_Mile_Carrier__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Aloc_COGS_Provider__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_zloc_cogs_provider(es_value: Any, context: dict = None) -> Optional[str]:
    """
    Transform ES Last_Mile_Carrier__c to BBF Zloc_COGS_Provider__c.

    ES Field: Last_Mile_Carrier__c (Last Mile Carrier)
    ES Type: reference

    BBF Field: Zloc_COGS_Provider__c (Zloc COGS Provider)
    BBF Type: string
    BBF Required: No

    AI Reasoning:
    Z-location COGS provider - may derive from Last_Mile_Carrier__c if location-specific

    Args:
        es_value: The source value from ES Last_Mile_Carrier__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Zloc_COGS_Provider__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


def transform_off_net(es_value: Any, context: dict = None) -> Optional[Any]:
    """
    Transform ES OFF_NET_IDs__c to BBF Off_Net__c.

    ES Field: OFF_NET_IDs__c (OFF-NET IDs)
    ES Type: string

    BBF Field: Off_Net__c (Off-Net)
    BBF Type: reference
    BBF Required: No

    AI Reasoning:
    Off-Net relationship - derive from OrderItem OFF_NET_IDs__c field

    Args:
        es_value: The source value from ES OFF_NET_IDs__c
        context: Optional dict with additional record context

    Returns:
        Transformed value suitable for BBF Off_Net__c
    """
    # Handle null/empty input
    if es_value is None or (isinstance(es_value, str) and not es_value.strip()):
        return None

    # Pass through with basic type handling
    return es_value


# Transformer registry
TRANSFORMERS = {
    'Description__c': transform_description,
    'Sequence__c': transform_sequence,
    'Amount__c': transform_amount,
    'PricebookEntryId__c': transform_pricebookentryid,
    'Charge_Class__c': transform_charge_class,
    'Charge_Active__c': transform_charge_active,
    'Product_Category__c': transform_product_category,
    'Product_Name__c': transform_product_name,
    'Product__c': transform_product,
    'Bill_Schedule_Type__c': transform_bill_schedule_type,
    'Service_Order_Line_Charge__c': transform_service_order_line_charge,
    'MRC_Net__c': transform_mrc_net,
    'NRC_Net__c': transform_nrc_net,
    'Active__c': transform_active,
    'Start_Date_Achieved_On__c': transform_start_date_achieved_on,
    'End_Date_Achieved_On__c': transform_end_date_achieved_on,
    'Aloc_COGS_Provider__c': transform_aloc_cogs_provider,
    'Zloc_COGS_Provider__c': transform_zloc_cogs_provider,
    'Off_Net__c': transform_off_net
}

# Field mapping (BBF -> ES)
FIELD_MAPPING = {
    'Description__c': 'Description',
    'Sequence__c': 'OrderItemNumber',
    'Amount__c': 'Total_MRC_Amortized__c',
    'PricebookEntryId__c': 'PricebookEntryId',
    'Charge_Class__c': 'SBQQ__ChargeType__c',
    'Charge_Active__c': 'SBQQ__Activated__c',
    'Product_Category__c': 'Product_Family__c',
    'Product_Name__c': 'Product_Name__c',
    'Product__c': 'Product2Id',
    'Bill_Schedule_Type__c': 'SBQQ__BillingFrequency__c',
    'Service_Order_Line_Charge__c': 'SBQQ__QuoteLine__c',
    'MRC_Net__c': 'Total_MRC_Amortized__c',
    'NRC_Net__c': 'NRC_Non_Amortized__c',
    'Active__c': 'SBQQ__Activated__c',
    'Start_Date_Achieved_On__c': 'ServiceDate',
    'End_Date_Achieved_On__c': 'EndDate',
    'Aloc_COGS_Provider__c': 'Last_Mile_Carrier__c',
    'Zloc_COGS_Provider__c': 'Last_Mile_Carrier__c',
    'Off_Net__c': 'OFF_NET_IDs__c'
}


def apply_transformers(es_record: dict) -> dict:
    """
    Apply all transformers to an ES record.

    Args:
        es_record: Dictionary of ES field values (field API name -> value)

    Returns:
        Dictionary of transformed BBF field values (BBF field API name -> value)
    """
    bbf_record = {}

    for bbf_field, transformer in TRANSFORMERS.items():
        es_field = FIELD_MAPPING.get(bbf_field)
        if es_field and es_field in es_record:
            try:
                bbf_record[bbf_field] = transformer(es_record[es_field], es_record)
            except Exception as e:
                # Log error but continue with other fields
                print(f"Warning: Transform failed for {bbf_field}: {e}")
                bbf_record[bbf_field] = None

    return bbf_record
